### ISSUE TITLE
Feature Request: extend search to filter by cookie content

### ISSUE THREAD

**Issue by scheinercc** [ysard/cookie-quick-manager#14]
Heya,

Would it possible to filter by cookie content? E.g. if I wanted to delete all __utma cookies it would be handy to just filter for "__utma", select all results and hit a delete button.

Cheers

**Comment by ysard** [comment]
Hi, I'm trying to implement this feature, here is a draft of the interface:

![image](https://user-images.githubusercontent.com/14988285/45969202-4b0fec80-c033-11e8-8bca-d9fdf18a292a.png)

The interface is likely to change if it is not understandable enough.

It allows forging a query that will search in the names or values of cookies in addition to the domain name.
If you specify multiple 'name' or 'value' filters, these will be linked by an OR operator, but if you specify a 'name' filter and a 'value' filter, these will be queried with a logical AND.

**Comment by scheinercc** [comment]
Cool! Thanks for all your efforts.
Is the overlay "Search term: [blue bordered input] in cookie..." the search field and the other one on top with :name:"utm" just for displaying the current search?
It would be simpler to only have the top input field and to not have to select between names and values, but if by default both would get searched.
:name: and :value: could be documented special searches, like site: in search engines.

What do you think?

**Comment by ysard** [comment]
In fact the menu (likely to be modified) is used to forge the query that is inserted in the usual search field.
Basically, either you type yourself _': name: xxx'_ or you go through the menu by typing directly _'xxx'_ and then clicking on the item _'name'_. The system is similar to that of GitHub for filtering issues.

I think searching for default names, values, and domains will be disturbing since we have a list of domains below, and the most common use case is domain search.

**Comment by ysard** [comment]
It is now implemented in the last version available; feel free to reopen this issue if the feature needs an update.
