### ISSUE TITLE
Request for Autoreload

### ISSUE THREAD

**Issue by horshack** [ysard/cookie-quick-manager#30]
I am using Cookie Quick Manager as a developer tool to see which cookie my own software sends. Pressing F5 to reload the cookie-status is stressys, a button for Autoreload every seconds would be great. There ist a reload button on top of the window, please add a second button labeled with an "auto".

**Comment by ysard** [comment]
Hi, a refresh function at regular intervals will prevent the user from editing a cookie since this will reload the entire list of domains and then select the first item in the list (nevertheless, taking into account the current search filter).

What I can do is try to capture the add/delete events to reload the domain list or just the selected domain if it is concerned, and to reload only the current cookie if it is modified.

**Comment by ysard** [comment]
This feature will be in the next release. Feel free to reopen this issue if it is not what you expected :)

**Comment by Smile4ever** [comment]
@ysard How does it work? How do I activate it?

**Comment by ysard** [comment]
@Smile4ever You just have to check the checkbox "Auto-refresh" on top of the CQM tab/window.

**Comment by Smile4ever** [comment]
![image](https://user-images.githubusercontent.com/544411/59924047-1cde0280-9435-11e9-8805-3aa29aeece63.png)

Where should I see it? I just installed it from AMO.

**Comment by ysard** [comment]
Here it is just the menu of CQM, with some quick access options.
The main interface can be opened by clicking on "Manage all cookies".

An interface to view cookies from this menu (like the addons uBlock origin, uMatrix, NoScript, etc.) is still a work in progress,, but given the number of elements to display, it is now easier to have an independent window/tab (see in the options to open CQM in a window or a tab).

**Comment by Smile4ever** [comment]
I just want to reload the page when I've deleted the cookies using "Delete current SIte Cookies". Is that something you can implement using a preference?

**Comment by ysard** [comment]
Oh, it's not CQM that you want to recharge.
I think that implementing it is not really worth it since a user can just press F5.
In most cases, erasing cookies does not change the interface of a site, reloading the page is not a priority as is the case with an adblocker (with the current interface anyway).

**Comment by Smile4ever** [comment]
Okay, thanks anyway for your explanations.
