### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by exploide** [ysard/cookie-quick-manager#39]
Just stumbled upon this extension and it looks very promising! In conjunction with Mozilla's Multi Account Containers, it can be useful when analyzing a web application's session management.

I would like to propose some design improvements.

- When the browser uses kind of a dark style by default, the icons and button labels are barely readable. See screenshot. Maybe it can be inverted to white when button color is too dark?!
![screenshot from 2018-09-12 15-52-11](https://user-images.githubusercontent.com/5670236/45429555-d8eaef80-b6a3-11e8-9edd-a6748a7ae8f6.png)

- As a workaround, I switched to "Hacker style". While this hurts my eyes a bit :wink: , it also has the drawback that you cannot distinguish grayed out fields from enabled fields.

- Besides, the Cookies column in the middle could probably be improved in terms of readability. I'm not a design expert so I have no clear idea here. But maybe one could at least make the cookie name and value visually distinct. Especially for long complex cookie values, it's hard to spot where the name ends and the value begins. (As a side note, I'm also a fan of the cookie table view from Firefox' dev tools, but don't know if it would make sense to incorporate a similar view into the cookie manager)

**Comment by ysard** [comment]
Hi, thank you for the review!

- Indeed the contrast in this example is catastrophic, it is curious whereas this is managed by bootstrap; I will see to fix the color.

- The hackerstyle is more a demonstration that the style can be changed quite easily than anything else; I will see to fix the contrasts there too.

- What do you think about displaying names in bold and italicized content?

The tables were the choice of [Cookie Manager+](https://addons.mozilla.org/fr/firefox/addon/cookies-manager-plus/) however it is not planned to develop a new interface of this type for the moment (too time-consuming) :)

**Comment by exploide** [comment]
Great, thanks for your reply.

I also thought about displaying name in bold. But italicized value could easily look odd. Cannot fully imagine the latter but perhaps leave it normal. However, while displaying the name in bold would be an improvement, I'm still not sure if this looks nice. What about the first equal sign then? Maybe twoline? First line shows name in bold, second line shows value? Could look cleaner but on the other hand increases the necessary space for showing one cookie... Don't know.

Yeah, the table view was only an idea as it allows to quickly gain an overview. But it's not important and of course up to you. Probably the UI will slowly enhance over time?!

**Comment by ysard** [comment]
Well here are the two possibilities for the middle column:

![two lines](https://user-images.githubusercontent.com/14988285/45600164-73c33100-b9f8-11e8-83b0-23a83b252b4d.png)

or

![one line](https://user-images.githubusercontent.com/14988285/45600171-a8cf8380-b9f8-11e8-9538-8a78947eb6b9.png)

I do not know what to choose: p

**Comment by exploide** [comment]
I'm also not the right person when it comes to style decisions :D

Think both are fine. Guess I like the two line approach a bit more, but the other one is also better than the previous styling.

Thanks for addressing my suggestions.

**Comment by ysard** [comment]
Finally I opted for the solution on only 1 line, because some domains contain a lot of cookies and the gain of space is important :)

**Comment by Boruch-Baum** [comment]
I've hacked the css to provide a dark theme that seems to work. Unfortunately, the modifications span several files: menu.html, options.html, and hacker_style.css.

My suggestion would be remove the hard-coded css from the all the html files, and to move them to a single css file "default.css", which would be a template for hacker_style.css, meaning that all the entries currently in hacker_style.css would exist in default.css but with their default values. Then, add to the options.html a "user-defined.css" that would point to a file outside the xpi blob, say ~/.mozilla/extensions/cookie-quick-manager/user-defined.css. Also, because it's common for people to be using a dark theme, you may want to also add a dark-theme.css within the xpi blob, along with an entry in the options.html

That way, a user could define a custom skin without having to mess with the xpi blob, and without having to keep updating it every time the extension is updated. For now, if I want to keep my dark theme, which I really prefer, it will be a pain every time I update the extension.

I'm happy to share the changes I've made as a diff ; I haven't proposed this as a PR because: a) I'm lazy; b) I would want to know first whether you're even interested; c) it's real simple, and you may want to do it your way anyway.

Edit: Ooops, should maybe have told you at the beginning that I think this extension is great, and thanks for writing it.
