### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Boruch-Baum** [ysard/cookie-quick-manager#51]
See my comment here: https://github.com/ysard/cookie-quick-manager/issues/39#issuecomment-450274092

**Comment by ysard** [comment]
Hi, 
for the moment, the design is only for the main window.
You could propose your theme if you consider it successful, so that I can integrate it; I could also consider a custom field in which a user could paste his own CSS design.
The design changes of the drop-down menu are currently a little more delicate as indeed, it is not subject to a dynamic design.

**Comment by Boruch-Baum** [comment]
Just now went to start on it using git, in order to make a formal pull request, but I'm confused which branch to use, because the current site default isn't master, but 'fpi'. What gives? I mean, what's is the organization structure of the branches, and which should I work from?

**Comment by ysard** [comment]
Sorry for the delay, I do not develop on master, so the merge is not for now. Since people want to easy see the repository in its most recent state, I put the dev branch (fpi) as the default branch.
I close this issue and I am looking at your pull-request as soon as possible.
