### ISSUE TITLE
Cookie Quick Manager 0.4rc2 popup menu issue

### ISSUE THREAD

**Issue by ghost** [ysard/cookie-quick-manager#56]
Hi,

Cookie Quick Manager 0.4rc2 / Firefox 65 (64-bit) / Winndows 7 (64-bit)

I've just updated Cookie Quick Manager from 0.4rc1 to 0.4rc2 and I can no longer access the _**Manage all Cookies**_ from the extension's popup menu:

![cqm-0 4rc2](https://user-images.githubusercontent.com/42912760/52339706-23cc2180-2a0e-11e9-91ce-4d77ea2763d2.jpg)

Clicking on _Manage all cookies_ is inoperative.
Downgrading to Cookie Quick Manager 0.4rc1 solves the issue.

Thanks.

EDIT: the popup menu _Manage all Cookies_ link appears to work randomly. The popup itself displays correctly randomly as well (occasionally white, no menu item, but this happens with other extensions even if it appeared less with previous CQM 0.4rc1)

I'm downgrading to 0.4rc1 for the time being with which I never encountered the slightest issue.
.

**Comment by ysard** [comment]
Hi, there is indeed a problem with the menu (it works when you click outside the text...), i pushed this version too soon.
Thank you very much for the issue.
The version 0.4rc2 is now disabled on AMO.

I have never encountered the problem of the popup white menu but this may be related to a problem already encountered for the windowed mode of CQM. This is a recurring problem since Quantum which should be solved since version 63:
https://bugzilla.mozilla.org/show_bug.cgi?id=1425829
https://bugzilla.mozilla.org/show_bug.cgi?id=1408446

**Comment by ghost** [comment]
@ysard, thanks  for the links pertaining to the popup white menu. As I mentioned above this is not specific to CQM, concerns several of my 40+ extensions (when applicable of course), appears randomly (I sometimes have to click 3 times on the toolbar button) and i still haven't managed to find the culprit. It appears very very occasionally with CQM 0.4rc1 ... but, again, this is a Quantum issue.

Thanks for _Cookie Quick Manager_

**Comment by ysard** [comment]
This should be fixed now (0.4rc3 is currently being verified on AMO).
Thanks :)
