### ISSUE TITLE
GJ you made me delete all the cookies from my browser

### ISSUE THREAD

**Issue by SBI-boy** [ysard/cookie-quick-manager#58]
I just noticed a new option to "delete current context cookies" in the toolbar I clicked on it and boom!! all my sessions were gone without even a confirmation popup.  You could do a better job explaining what that option means and give a strong warning before using it.

![sin titulo](https://user-images.githubusercontent.com/13672854/52546980-c92a2100-2d91-11e9-9397-fe135e012463.png)

**Comment by ysard** [comment]
Although the text "Current Context Cookies" seems to be quite explicit, an alert when removing cookies from a context from the context menu was added.
This alert is managed in the same way as in the main interface: via the "Display an alert before removing cookies from entire browsing context (s)" option.

![modal_alert](https://user-images.githubusercontent.com/14988285/59622509-07fe2800-9132-11e9-9a75-1e5b3d189943.jpg)

https://xkcd.com/1172/ :p

**Comment by SpaceClicker** [comment]
Perhaps you can display the number of cookies that will be erased in this warning?  That will be an extra indication that ALL cookies in the context (a term that some may not be completely familiar with) will be erased and not just those currently displayed due to the search filter.

In fact, maybe it would be better to have this option delete all cookies listed by the current filter, in that way you can change the context and leave the filter blank to get the current functionality, and filter it to just erase cookies in the current context that match the filter.

**Comment by ysard** [comment]
@SpaceClicker Hi, this feature should be clearer now.
Search filters are indeed taken into account.
Feel free to reopen the issue in case of new concern ;)
