### ISSUE TITLE
popup menu still cutting off lines

### ISSUE THREAD

**Issue by bendover22** [ysard/cookie-quick-manager#60]
Issue 56 is still a problem for me in 0.4rc4.
The last? line in the menu is cut off, in Fx 65.0.1, Mint 18.1.

Maybe because of a fixed height, but I see other addons that also show a "height=" and a "min-height=", and they don't cut off content.  The box doesn't seem to be flexing like it should.

Maybe the 157px is just too short?  Maybe using ems instead of px, so the box can accommodate different fonts & sizes. 
![image](https://user-images.githubusercontent.com/1909407/54482574-9d2c1080-4813-11e9-96da-bb2b563a4f2a.png)

**Comment by ghost** [comment]
Following fixes the issue here with _Cookie Quick Manager_ 0.4rc4 / Firefox 67.0 (x64) / Windows 7 (x64)

In [Firefox user profile] / chrome / userContent.css (create if not present), add:

```
/* COOKIE QUICK MANAGER – ADD-ONS FOR FIREFOX */
@-moz-document url("moz-extension://[Internal UUID]/menu.html") {
body {height: auto !important;}
}
```

For those who don't know what an extension's [Internal UUID] is, they're all available in Firefox's about:debugging

Anyway the default body `{height: 157px;}` is too short here, the last item, _Options_, doesn't appear within 157px, so either increase or set to _auto_, which does it here. 

EDIT:

I still notice a delay, stall once in a while. Seems to be improved if not totally resolved by setting the width as well, which leads to:
```
/* COOKIE QUICK MANAGER – ADD-ONS FOR FIREFOX */
@-moz-document url("moz-extension://[Internal UUID]/menu.html") {
body {height: auto !important;  min-width:0px !important; width:auto !important;}
}
```

To remove the favicons (essentially cosmetically subjective), add:
`.favicon {display:none !important;}`

To remove the hover shadow and enforce the background color of hovered items, add:
`a:hover {box-shadow:none !important; background-color:#E0E0FF !important;}`

Now we have a nice case which opens nicely as well for a brilliant gem :=)

**Comment by ysard** [comment]
Hi, sorry for the delay, my time is currently very limited.

Thank you for reporting the bug, the height is indeed set independently of the font used.
From now on it will be automatic.

However I am more reserved about a similar parameter for the width.
This menu takes time to display because of requests on cookies (the number of cookies displayed to the right of some entries), it often produces a lag and uncomfortable resizing. These functions are asynchronous but heavy, I do not really know how to speed up that. Setting a globally acceptable width for most sites reduces the frequency of unsightly resizing.

Another addon that seems to suffer from this: NoScript.
