### ISSUE TITLE
Error: Extension disallowed access 

### ISSUE THREAD

**Issue by grandemestre** [ysard/cookie-quick-manager#63]
I try to use the extension but it does not work. No cookie appears in the popup and in the console log the message appears
Error: "Extension disallowed access to the private storeId cookies." api.js: 242: 31

I do not know if it can be relevance but my Firefox is version 67.0.1

**Comment by SpaceClicker** [comment]
Go to the add-ons page, click on the "Cookie Quick Manager" add-on to get to the details page for the add-on, scroll down to the part that says "Run in Private Windows" and select the "Allow" option.

Until I did this the "All" context would not show anything and some of the other contexts would also be missing cookies.  I assume this is because when it tried to enumerate all the cookies, it would hit the "private" cookies and was denied access and instead of just continuing it would halt/crash the add-on.

**Comment by grandemestre** [comment]
> Go to the add-ons page, click on the "Cookie Quick Manager" add-on to get to the details page for the add-on, scroll down to the part that says "Run in Private Windows" and select the "Allow" option.
> 
> Until I did this the "All" context would not show anything and some of the other contexts would also be missing cookies. I assume this is because when it tried to enumerate all the cookies, it would hit the "private" cookies and was denied access and instead of just continuing it would halt/crash the add-on.

thank you very much. This worked perfectly

**Comment by ysard** [comment]
@SpaceClicker 
Thanks for the help, I am currently working on this problem. 

The option to allow addons in private browsing is recent in firefox and a priori only newly installed addons explicitly request permission.
