### ISSUE TITLE
List of Domains is empty

### ISSUE THREAD

**Issue by iG8R** [ysard/cookie-quick-manager#64]
Hi. The same issue as mentioned in [#23](https://github.com/ysard/cookie-quick-manager/issues/23) :(
Firefox 67.0.1 (64-bit) Win10 64bit
privacy.firstparty.isolate;**false**

**Comment by SpaceClicker** [comment]
Try doing this to see if it fixes your issue:

Go to the add-ons page, click on the "Cookie Quick Manager" add-on to get to the details page for the add-on, scroll down to the part that says "Run in Private Windows" and select the "Allow" option.

**Comment by iG8R** [comment]
Thank you! It works now.

**Comment by SpaceClicker** [comment]
You're welcome.  The add-on should probably be fixed so that it either tells you to "allow" that option, or so that it will not fail if that option is not "allow"ed.

**Comment by ysard** [comment]
Thank you for reporting the problem.

The option to allow addons in private browsing is recent in firefox and a priori only newly installed addons explicitly request permission.

**Comment by Killogy** [comment]
@ysard
I´m running Firefox 56.0.2 64bits and latest CQM version 0.5rc1 is not working properly because List of Domains is empty. Reinstalling 0.4rc4 fixed this issue.
![version cookie](https://user-images.githubusercontent.com/32386526/59960486-2b75f980-94c9-11e9-8828-612064960944.jpg)

Also, if I uninstall 0.5rc1 version and reinstall 0.4rc4 protected cookies becomes unprotected, to avoid this I must to install 0.4rc4 version without uninstalling 0.5rc1 version.

**Comment by ysard** [comment]
Hi thank you for the bug report;

I just tested and indeed there is a concern with an error due to the use of a recent ECMAScript feature supported only from Firefox 58.

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Promise/finally

This function is used to avoid code redondancy in CQM.

- I will revert this patch in the next version...
- When you uninstall an addon, all its data are deleted; when you install another version of the addon there is not deletion. It's the normal process.

- Note: Firefox 56 is very very old now, many updates and improvements have been published since this release ;)
