### ISSUE TITLE
No cookies appear in the popup

### ISSUE THREAD

**Issue by jhhughes** [ysard/cookie-quick-manager#67]
Hi, similar problem to issue #63 in that "No cookies appear in the popup", but on Waterfox 56.

This appears to be related to the 0.5rc1 changes addressing #63 as rolling back to 0.4rc4 rectifies the problem.

**Comment by ysard** [comment]
Hi thanks for the bug report, Waterfox 56 is supposed to be based on Firefox 56.02;
(seen here: https://www.waterfox.net/blog/waterfox-56.0-release-download)

This is an old version now, but the bug you mention is due to the lack of use of the following feature in version 0.4x, yet present in Firefox since version 48:

https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/extension/isAllowedIncognitoAccess

Could you give me the error generated by the console (Ctrl + Shift + J, then clean the output by clicking on the small trash, then actualize CQM).

I will see for myself by installing Waterfox.

**Comment by ysard** [comment]
Ok, this is related to #64; It should be fixed in the next release ;)
